
---

- name: DIR
  become: true
  vars_prompt:
    - name: FOLDER
      prompt: "Which folder to look into?"
      private: no
           

  hosts: all
  

  tasks:
     - name: CHECK CONTENT INSIDE FOLDER1
       shell: "ls -la {{ FOLDER }}"
       register: var1

     - name:
       debug:
         var: var1
         verbosity: 2
